=== ChernihVyacheslav/Epam-practice7/input.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--  XML schema -->

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://nure.ua/chernykh/practice7"
            xmlns:tns="http://nure.ua/chernykh/practice7">

    <xsd:element name="Medicines">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="Medicine"
                             type="tns:Medicine" maxOccurs="unbounded"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:complexType name="Medicine">
        <xsd:sequence>
            <xsd:element name="MedicineName" type="xsd:string"/>
            <xsd:element name="MedicineGroup" type="xsd:string"/>
            <xsd:element name="MedicinePharm" type="xsd:string"/>
            <xsd:sequence>
                <xsd:element name="MedicineAnalog" type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
            </xsd:sequence>
            <xsd:sequence>
                <xsd:element name="MedicineVersion" type="tns:MedicineVersion" maxOccurs="unbounded"/>
            </xsd:sequence>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="MedicineVersion">
        <xsd:sequence>
            <xsd:element name="MedicineVersionName" type="xsd:string"/>
            <xsd:element name="PharmVersion" type="tns:PharmVersion" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="PharmVersion">
        <xsd:sequence>
            <xsd:element name="PharmName" type="xsd:string"/>
            <xsd:element name="PharmCertificate" type="tns:PharmCertificate"/>
            <xsd:element name="MedicinePackage" type="tns:MedicinePackage"/>
            <xsd:element name="MedicineDosage" type="tns:MedicineDosage"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="PharmCertificate">
        <xsd:sequence>
            <xsd:element name="CertificateNumber" type="xsd:positiveInteger"/>
            <xsd:element name="CertificateStartDate" type="xsd:date"/>
            <xsd:element name="CertificateEndDate" type="xsd:date"/>
            <xsd:element name="CertificateOrganisation" type="xsd:string"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="MedicinePackage">
        <xsd:sequence>
            <xsd:element name="PackageType" type="xsd:string"/>
            <xsd:element name="MedicineAmount" type="xsd:positiveInteger"/>
            <xsd:element name="MedicinePrice" type="xsd:decimal"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="MedicineDosage">
        <xsd:sequence>
            <xsd:element name="DoseAmount" type="xsd:positiveInteger"/>
            <xsd:element name="DosagePeriodicity">
                <xsd:complexType>
                    <xsd:simpleContent>
                        <xsd:extension base="xsd:positiveInteger">
                            <xsd:attribute name="periodicityType" type="xsd:string"/>
                        </xsd:extension>
                    </xsd:simpleContent>
                </xsd:complexType>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>
</xsd:schema>

=== ChernihVyacheslav/Epam-practice7/input.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--  Input XML document. This XML is valid against Test.xsd XML schema-->

<p7:Medicines xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns:p7="http://nure.ua/chernykh/practice7"
         xsi:schemaLocation="http://nure.ua/chernykh/practice7 input.xsd">

    <Medicine>
        <MedicineName>Болеуталяющее1</MedicineName>
        <MedicineGroup>Болеуталяющие</MedicineGroup>
        <MedicinePharm>Pharm1</MedicinePharm>
        <MedicineAnalog>БолеуталяющееАналог1</MedicineAnalog>
        <MedicineAnalog>БолеуталяющееАналог2</MedicineAnalog>
        <MedicineAnalog>БолеуталяющееАналог3</MedicineAnalog>
        <MedicineVersion>
            <MedicineVersionName>Капсулы</MedicineVersionName>
            <PharmVersion>
                <PharmName>Pharm1</PharmName>
                <PharmCertificate>
                    <CertificateNumber>111</CertificateNumber>
                    <CertificateStartDate>2019-06-06</CertificateStartDate>
                    <CertificateEndDate>2020-06-06</CertificateEndDate>
                    <CertificateOrganisation>Org1</CertificateOrganisation>
                </PharmCertificate>
                <MedicinePackage>
                    <PackageType>PackageType1</PackageType>
                    <MedicineAmount>10</MedicineAmount>
                    <MedicinePrice>9.99</MedicinePrice>
                </MedicinePackage>
                <MedicineDosage>
                    <DoseAmount>1</DoseAmount>
                    <DosagePeriodicity periodicityType="daily">3</DosagePeriodicity>
                </MedicineDosage>
            </PharmVersion>
        </MedicineVersion>
        <MedicineVersion>
            <MedicineVersionName>Таблетки</MedicineVersionName>
            <PharmVersion>
                <PharmName>Pharm1</PharmName>
                <PharmCertificate>
                    <CertificateNumber>222</CertificateNumber>
                    <CertificateStartDate>2019-06-06</CertificateStartDate>
                    <CertificateEndDate>2021-06-06</CertificateEndDate>
                    <CertificateOrganisation>Org2</CertificateOrganisation>
                </PharmCertificate>
                <MedicinePackage>
                    <PackageType>PackageType2</PackageType>
                    <MedicineAmount>20</MedicineAmount>
                    <MedicinePrice>7.88</MedicinePrice>
                </MedicinePackage>
                <MedicineDosage>
                    <DoseAmount>1</DoseAmount>
                    <DosagePeriodicity periodicityType="daily">3</DosagePeriodicity>
                </MedicineDosage>
            </PharmVersion>
        </MedicineVersion>
        <MedicineVersion>
            <MedicineVersionName>Порошок</MedicineVersionName>
            <PharmVersion>
                <PharmName>Pharm2</PharmName>
                <PharmCertificate>
                    <CertificateNumber>333</CertificateNumber>
                    <CertificateStartDate>2019-06-06</CertificateStartDate>
                    <CertificateEndDate>2019-12-06</CertificateEndDate>
                    <CertificateOrganisation>Org3</CertificateOrganisation>
                </PharmCertificate>
                <MedicinePackage>
                    <PackageType>PackageType3</PackageType>
                    <MedicineAmount>9</MedicineAmount>
                    <MedicinePrice>14.55</MedicinePrice>
                </MedicinePackage>
                <MedicineDosage>
                    <DoseAmount>1</DoseAmount>
                    <DosagePeriodicity periodicityType="daily">2</DosagePeriodicity>
                </MedicineDosage>
            </PharmVersion>
        </MedicineVersion>
    </Medicine>

    <Medicine>
        <MedicineName>Антибиотик1</MedicineName>
        <MedicineGroup>Антибиотики</MedicineGroup>
        <MedicinePharm>Pharm2</MedicinePharm>
<!--        <MedicineAnalogs>АнтибиотикАналог1</MedicineAnalogs>-->
<!--        <MedicineAnalogs>АнтибиотикАналог2</MedicineAnalogs>-->
<!--        <MedicineAnalogs>АнтибиотикАналог3</MedicineAnalogs>-->
        <MedicineVersion>
            <MedicineVersionName>Капсулы</MedicineVersionName>
            <PharmVersion>
                <PharmName>Pharm21</PharmName>
                <PharmCertificate>
                    <CertificateNumber>444</CertificateNumber>
                    <CertificateStartDate>2019-06-06</CertificateStartDate>
                    <CertificateEndDate>2019-12-06</CertificateEndDate>
                    <CertificateOrganisation>Org4</CertificateOrganisation>
                </PharmCertificate>
                <MedicinePackage>
                    <PackageType>PackageType1</PackageType>
                    <MedicineAmount>10</MedicineAmount>
                    <MedicinePrice>49.99</MedicinePrice>
                </MedicinePackage>
                <MedicineDosage>
                    <DoseAmount>1</DoseAmount>
                    <DosagePeriodicity periodicityType="daily">1</DosagePeriodicity>
                </MedicineDosage>
            </PharmVersion>
            <PharmVersion>
                <PharmName>Pharm22</PharmName>
                <PharmCertificate>
                    <CertificateNumber>666</CertificateNumber>
                    <CertificateStartDate>2019-06-06</CertificateStartDate>
                    <CertificateEndDate>2019-06-06</CertificateEndDate>
                    <CertificateOrganisation>Org5</CertificateOrganisation>
                </PharmCertificate>
                <MedicinePackage>
                    <PackageType>PackageType1</PackageType>
                    <MedicineAmount>12</MedicineAmount>
                    <MedicinePrice>74.99</MedicinePrice>
                </MedicinePackage>
                <MedicineDosage>
                    <DoseAmount>1</DoseAmount>
                    <DosagePeriodicity periodicityType="daily">1</DosagePeriodicity>
                </MedicineDosage>
            </PharmVersion>
        </MedicineVersion>
        <MedicineVersion>
            <MedicineVersionName>Таблетки</MedicineVersionName>
            <PharmVersion>
                <PharmName>Pharm21</PharmName>
                <PharmCertificate>
                    <CertificateNumber>555</CertificateNumber>
                    <CertificateStartDate>2019-06-06</CertificateStartDate>
                    <CertificateEndDate>2020-06-06</CertificateEndDate>
                    <CertificateOrganisation>Org4</CertificateOrganisation>
                </PharmCertificate>
                <MedicinePackage>
                    <PackageType>PackageType2</PackageType>
                    <MedicineAmount>20</MedicineAmount>
                    <MedicinePrice>37.88</MedicinePrice>
                </MedicinePackage>
                <MedicineDosage>
                    <DoseAmount>1</DoseAmount>
                    <DosagePeriodicity periodicityType="daily">2</DosagePeriodicity>
                </MedicineDosage>
            </PharmVersion>
            <PharmVersion>
                <PharmName>Pharm22</PharmName>
                <PharmCertificate>
                    <CertificateNumber>777</CertificateNumber>
                    <CertificateStartDate>2019-06-06</CertificateStartDate>
                    <CertificateEndDate>2021-06-06</CertificateEndDate>
                    <CertificateOrganisation>Org4</CertificateOrganisation>
                </PharmCertificate>
                <MedicinePackage>
                    <PackageType>PackageType2</PackageType>
                    <MedicineAmount>50</MedicineAmount>
                    <MedicinePrice>98.88</MedicinePrice>
                </MedicinePackage>
                <MedicineDosage>
                    <DoseAmount>1</DoseAmount>
                    <DosagePeriodicity periodicityType="daily">3</DosagePeriodicity>
                </MedicineDosage>
            </PharmVersion>
        </MedicineVersion>
    </Medicine>

    <Medicine>
        <MedicineName>ВитаминА</MedicineName>
        <MedicineGroup>Витамины</MedicineGroup>
        <MedicinePharm>Pharm3</MedicinePharm>
        <MedicineAnalog>ВитаминАналог1</MedicineAnalog>
        <MedicineAnalog>ВитаминАналог2</MedicineAnalog>
        <MedicineAnalog>ВитаминАналог3</MedicineAnalog>
        <MedicineVersion>
            <MedicineVersionName>Капсулы</MedicineVersionName>
            <PharmVersion>
                <PharmName>Pharm33</PharmName>
                <PharmCertificate>
                    <CertificateNumber>1111</CertificateNumber>
                    <CertificateStartDate>2019-06-06</CertificateStartDate>
                    <CertificateEndDate>2020-06-06</CertificateEndDate>
                    <CertificateOrganisation>Org33</CertificateOrganisation>
                </PharmCertificate>
                <MedicinePackage>
                    <PackageType>PackageType1</PackageType>
                    <MedicineAmount>20</MedicineAmount>
                    <MedicinePrice>19.99</MedicinePrice>
                </MedicinePackage>
                <MedicineDosage>
                    <DoseAmount>1</DoseAmount>
                    <DosagePeriodicity periodicityType="daily">3</DosagePeriodicity>
                </MedicineDosage>
            </PharmVersion>
        </MedicineVersion>
        <MedicineVersion>
            <MedicineVersionName>Таблетки</MedicineVersionName>
            <PharmVersion>
                <PharmName>Pharm33</PharmName>
                <PharmCertificate>
                    <CertificateNumber>2222</CertificateNumber>
                    <CertificateStartDate>2019-06-06</CertificateStartDate>
                    <CertificateEndDate>2021-06-06</CertificateEndDate>
                    <CertificateOrganisation>Org22</CertificateOrganisation>
